# Generated by Django 5.0.2 on 2025-02-20 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectsPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='assigned_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='defect',
            name='assigned_to',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='defect',
            name='defect_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='defect',
            name='defect_type',
            field=models.CharField(max_length=100),
        ),
    ]
