# Generated by Django 5.0.2 on 2025-02-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectsPortal', '0002_alter_defect_assigned_by_alter_defect_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='defect_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary')], default='PRIMARY', max_length=100),
        ),
        migrations.AlterField(
            model_name='defect',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'high'), ('MEDIUM', 'medium'), ('LOW', 'low')], default='HIGH', max_length=100),
        ),
    ]
