# Generated by Django 5.0.2 on 2025-02-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DefectsPortal', '0004_defects_screen_shots'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='defect_status',
            field=models.CharField(choices=[('COMPLETED', 'completed'), ('NOT COMPLETED', 'not completed')], default='NOT COMPLETED', max_length=100),
        ),
    ]
